/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData apps = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_to_dot_solid = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData balloons = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building__1_ = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business_time = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cake_birthday = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_days_solid__1_ = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox__1_ = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_check_regular = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_xmark_regular = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_regular = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_upload__2_ = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card__1_ = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cursor_finger = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamation = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye__2_ = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fingerprint = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData futbol_regular = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hastag__1_ = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hastag = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home__2_ = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass_end = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData interactive = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loading = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magic_wand__1_ = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_breastfeeding_solid = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_solid = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_call = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search__1_ = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seedling_solid__1_ = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_sliders = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_exclamation = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sign_out_alt = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stats = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up_regular = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_past = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users_alt = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData venus_mars = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_day_month_date_year_icon = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address_book = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ph_arrows_counter_clockwise_duotone = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_1 = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_exclamation_1 = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye__2__1 = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cursor_finger_1 = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bitmap = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData akar_icons_eye_closed = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData individual = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_info = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock2 = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
